behaviors:
  FetchGamePhysics:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          goal_conditioning_type: hyper
          deterministic: false
      rnd:
        learning_rate: 3e-4
        strength: 0.01
        gamma: 0.99
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          goal_conditioning_type: hyper
          deterministic: false
    keep_checkpoints: 5
    checkpoint_interval: 1000000
    max_steps: 5000000
    time_horizon: 128
    summary_freq: 10000
    threaded: false
environment_parameters:
  obstacle_scale_vs_ramp:
    curriculum:
      - name: LessonA
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 250
          threshold: 0
        value: 0.3
      - name: LessonB
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 0.2
        value: 0.4
      - name: LessonC
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 150
          threshold: 0.4
        value: 0.5
      - name: LessonD
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.6
        value: 0.55
      - name: LessonE
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.7
        value: 0.6
      - name: LessonF
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.75
        value: 0.65
      - name: LessonG
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.8
        value: 0.67
      - name: LessonFinal
        value: 0.7
  ball_fetched_threshold:
    curriculum:
      - name: LessonA
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 250
          threshold: 0
        value: 0.25
      - name: LessonB
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 0.2
        value: 0.22
      - name: LessonC
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 150
          threshold: 0.4
        value: 0.18
      - name: LessonD
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 150
          threshold: 0.6
        value: 0.16
      - name: LessonE
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.7
        value: 0.12
      - name: LessonF
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.75
        value: 0.05
      - name: LessonG
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.8
        value: 0.025
      - name: LessonFinal
        value: 0.02
  speed_bonus:
    curriculum:
      - name: LessonA
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 250
          threshold: 0
        value: 0.1
      - name: LessonB
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 0.2
        value: 0.12
      - name: LessonC
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 150
          threshold: 0.4
        value: 0.15
      - name: LessonD
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 150
          threshold: 0.6
        value: 0.18
      - name: LessonE
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.7
        value: 0.2
      - name: LessonF
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.75
        value: 0.25
      - name: LessonG
        completion_criteria:
          measure: reward
          behavior: FetchGamePhysics
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.8
        value: 0.3
      - name: LessonFinal
        value: 0.5
